apiVersion: v1
kind: Service
metadata:
  name: event-client-service
spec:
  selector:
    app: event-client
  ports:
    - protocol: TCP
      port: 80          # External access port
      targetPort: 80    # Container port (NGINX)
  type: LoadBalancer    # Use LoadBalancer to expose the website publicly