apiVersion: v1
kind: Service
metadata:
  name: event-api-service
spec:
  selector:
    app: event-api
  ports:
    - protocol: TCP
      port: 80         # Internal cluster port
      targetPort: 3001 # Container port
  type: ClusterIP      # Use ClusterIP for the API since the frontend will access it internally